//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Turnir
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ekipe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ekipe()
        {
            this.Igraci = new HashSet<Igraci>();
            this.Rasporedi = new HashSet<Rasporedi>();
            this.Rasporedi1 = new HashSet<Rasporedi>();
            this.Strijelci = new HashSet<Strijelci>();
        }
    
        public int Id { get; set; }
        public string Naziv { get; set; }
        public Nullable<int> GrupeId { get; set; }
        public Nullable<int> OdigraneUtakmice { get; set; }
        public Nullable<int> Pobjede { get; set; }
        public Nullable<int> Neriješeno { get; set; }
        public Nullable<int> Porazi { get; set; }
        public Nullable<int> PostignutiGolovi { get; set; }
        public Nullable<int> PrimljeniGolovi { get; set; }
        public Nullable<int> GolRazlika { get; set; }
        public Nullable<int> Bodovi { get; set; }
    
        public virtual Grupe Grupe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Igraci> Igraci { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rasporedi> Rasporedi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rasporedi> Rasporedi1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Strijelci> Strijelci { get; set; }
    }
}
