//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Turnir
{
    using System;
    using System.Collections.Generic;
    
    public partial class Igraci
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Igraci()
        {
            this.Strijelci = new HashSet<Strijelci>();
        }
    
        public int Id { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public Nullable<int> EkipeId { get; set; }
        public Nullable<int> BrojGolovaGrupa { get; set; }
        public Nullable<int> BrojGolovaKnockout { get; set; }
    
        public virtual Ekipe Ekipe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Strijelci> Strijelci { get; set; }
    }
}
