//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Turnir
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TurnirEntities2 : DbContext
    {
        public TurnirEntities2()
            : base("name=TurnirEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ekipe> Ekipe { get; set; }
        public virtual DbSet<Grupe> Grupe { get; set; }
        public virtual DbSet<Igraci> Igraci { get; set; }
        public virtual DbSet<Rasporedi> Rasporedi { get; set; }
        public virtual DbSet<Rezultati> Rezultati { get; set; }
        public virtual DbSet<Strijelci> Strijelci { get; set; }
    }
}
