//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Turnir
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rezultati
    {
        public int Id { get; set; }
        public Nullable<int> RasporediId { get; set; }
        public Nullable<int> GoloviDomacin { get; set; }
        public Nullable<int> GoloviGost { get; set; }
    
        public virtual Rasporedi Rasporedi { get; set; }
    }
}
