//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Turnir
{
    using System;
    using System.Collections.Generic;
    
    public partial class Strijelci
    {
        public int Id { get; set; }
        public int IgraciId { get; set; }
        public int EkipeId { get; set; }
        public Nullable<int> BrojGolova { get; set; }
    
        public virtual Ekipe Ekipe { get; set; }
        public virtual Igraci Igraci { get; set; }
    }
}
